In [3]:
import pandas as pd

hourly = pd.read_excel("../data/raw/hourly_original.xlsx", skiprows=9)
hourly.head()

C:\Users\ebteh\miniconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Start date,End date,Germany/Luxembourg [€/MWh],∅ DE/LU neighbours [€/MWh],Belgium [€/MWh],Denmark 1 [€/MWh],Denmark 2 [€/MWh],France [€/MWh],Netherlands [€/MWh],Norway 2 [€/MWh],Austria [€/MWh],Poland [€/MWh],Sweden 4 [€/MWh],Switzerland [€/MWh],Czech Republic [€/MWh],DE/AT/LU [€/MWh],Northern Italy [€/MWh],Slovenia [€/MWh],Hungary [€/MWh]
0,"Jan 1, 2020 12:00 AM","Jan 1, 2020 1:00 AM",41.88,36.23,41.88,33.42,33.42,41.88,41.88,31.82,41.88,34.95,28.78,35.42,33.20,-,41.88,41.88,33.55
1,"Jan 1, 2020 1:00 AM","Jan 1, 2020 2:00 AM",38.60,34.30,38.60,31.77,31.77,38.60,38.60,31.77,38.60,34.67,28.45,34.04,30.40,-,38.60,38.60,30.40
2,"Jan 1, 2020 2:00 AM","Jan 1, 2020 3:00 AM",36.55,32.92,36.55,31.57,31.57,36.55,36.55,31.57,36.55,33.30,27.90,31.52,28.53,-,36.55,36.55,28.53
3,"Jan 1, 2020 3:00 AM","Jan 1, 2020 4:00 AM",32.32,30.75,32.32,31.28,31.28,32.32,32.32,31.28,32.32,31.91,27.52,28.29,27.37,-,32.32,32.32,27.37
4,"Jan 1, 2020 4:00 AM","Jan 1, 2020 5:00 AM",30.85,29.47,30.85,30.85,30.85,30.85,30.85,30.72,30.85,27.54,27.54,26.92,26.38,-,30.85,30.85,26.38

In [4]:
hourly = hourly[["Start date", "Germany/Luxembourg [€/MWh]"]]
hourly.head()

             Start date  Germany/Luxembourg [€/MWh]
0  Jan 1, 2020 12:00 AM                       41.88
1   Jan 1, 2020 1:00 AM                       38.60
2   Jan 1, 2020 2:00 AM                       36.55
3   Jan 1, 2020 3:00 AM                       32.32
4   Jan 1, 2020 4:00 AM                       30.85

In [5]:
hourly.columns = ["timestamp", "price"]
hourly.head()

              timestamp  price
0  Jan 1, 2020 12:00 AM  41.88
1   Jan 1, 2020 1:00 AM  38.60
2   Jan 1, 2020 2:00 AM  36.55
3   Jan 1, 2020 3:00 AM  32.32
4   Jan 1, 2020 4:00 AM  30.85

In [7]:
hourly["timestamp"] = pd.to_datetime(hourly["timestamp"], format="%b %d, %Y %I:%M %p", errors="coerce")
hourly["price"] = pd.to_numeric(hourly["price"], errors="coerce")

In [8]:
hourly.info()

<class 'pandas.DataFrame'>
RangeIndex: 50399 entries, 0 to 50398
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  50399 non-null  datetime64[us]
 1   price      50399 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 787.6 KB

In [9]:
hourly = hourly.dropna().reset_index(drop=True)
hourly.head()

            timestamp  price
0 2020-01-01 00:00:00  41.88
1 2020-01-01 01:00:00  38.60
2 2020-01-01 02:00:00  36.55
3 2020-01-01 03:00:00  32.32
4 2020-01-01 04:00:00  30.85

In [10]:
hourly.to_csv("../data/clean/hourly_clean.csv", index=False)

In [11]:
qh = pd.read_csv("../data/clean/qh_clean.csv")
qh.head()
qh.info()

<class 'pandas.DataFrame'>
RangeIndex: 13444 entries, 0 to 13443
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      13444 non-null  str
 1   price_eur_mwh  13444 non-null  str
dtypes: str(2)
memory usage: 210.2 KB

In [17]:
qh = pd.read_excel("../data/raw/qh_original.xlsx", skiprows=9)
qh.head()

C:\Users\ebteh\miniconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Start date,End date,Germany/Luxembourg [€/MWh],∅ DE/LU neighbours [€/MWh],Belgium [€/MWh],Denmark 1 [€/MWh],Denmark 2 [€/MWh],France [€/MWh],Netherlands [€/MWh],Norway 2 [€/MWh],Austria [€/MWh],Poland [€/MWh],Sweden 4 [€/MWh],Switzerland [€/MWh],Czech Republic [€/MWh],DE/AT/LU [€/MWh],Northern Italy [€/MWh],Slovenia [€/MWh],Hungary [€/MWh]
0,"Oct 1, 2025 12:00 AM","Oct 1, 2025 12:15 AM",102.6,95.01,102.68,102.60,102.44,102.08,102.55,68.61,108.87,98.95,58.11,101.00,97.21,-,113.60,109.10,108.98
1,"Oct 1, 2025 12:15 AM","Oct 1, 2025 12:30 AM",92.24,87.2,92.25,92.24,92.10,91.65,92.17,67.13,97.08,91.13,54.30,101.00,88.10,-,108.55,97.24,97.08
2,"Oct 1, 2025 12:30 AM","Oct 1, 2025 12:45 AM",86.03,79.5,80.47,86.03,85.90,63.14,82.69,64.43,97.07,81.79,53.05,101.00,78.98,-,101.61,96.22,90.97
3,"Oct 1, 2025 12:45 AM","Oct 1, 2025 1:00 AM",85.39,80.86,79.53,85.39,85.27,61.25,81.86,63.94,97.04,102.85,53.35,101.00,77.95,-,97.04,96.14,90.6
4,"Oct 1, 2025 1:00 AM","Oct 1, 2025 1:15 AM",89.99,85.14,89.28,89.99,89.85,86.91,89.54,65.59,92.78,93.98,52.23,98.46,87.92,-,108.61,92.51,91.15

In [18]:
qh = qh[["Start date", "Germany/Luxembourg [€/MWh]"]]

In [19]:
qh.columns = ["timestamp", "price"]

In [21]:
qh["timestamp"] = pd.to_datetime(
    qh["timestamp"],
    format="%b %d, %Y %I:%M %p",
    errors="coerce"
)
qh["price"] = pd.to_numeric(qh["price"], errors="coerce")

In [22]:
qh.info()
qh.head()

<class 'pandas.DataFrame'>
RangeIndex: 13444 entries, 0 to 13443
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  13444 non-null  datetime64[us]
 1   price      13156 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 210.2 KB

            timestamp   price
0 2025-10-01 00:00:00  102.60
1 2025-10-01 00:15:00   92.24
2 2025-10-01 00:30:00   86.03
3 2025-10-01 00:45:00   85.39
4 2025-10-01 01:00:00   89.99

In [23]:
qh = qh.dropna().reset_index(drop=True)

In [24]:
qh.to_csv("../data/clean/qh_clean.csv", index=False)