In [2]:
import pandas as pd

file_path = "../data/raw/QuarterHourly.xlsx"

df = pd.read_excel(file_path)

df.head()

C:\Users\ebteh\miniconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Datenkategorie: Großhandelspreise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Region: DE-LU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zeitraum: 01.10.2025 00:00 - 01.03.2026 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stand: 21.04.2026 14:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(c) Bundesnetzagentur | SMARD.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Auflösung: Viertelstunde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(14509, 19)

In [4]:
df.columns

Index(['Datenkategorie: Großhandelspreise', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18'],
      dtype='str')

In [5]:
df.head(20)

,Datenkategorie: Großhandelspreise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Region: DE-LU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zeitraum: 01.10.2025 00:00 - 01.03.2026 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stand: 21.04.2026 14:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(c) Bundesnetzagentur | SMARD.de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Auflösung: Viertelstunde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Berechnete Auflösung:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Originalauflösung: Deutschland/Luxemburg, Öste...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Datum von,Datum bis,Deutschland/Luxemburg [€/MWh],∅ Anrainer DE/LU [€/MWh],Belgien [€/MWh],Dänemark 1 [€/MWh],Dänemark 2 [€/MWh],Frankreich [€/MWh],Niederlande [€/MWh],Norwegen 2 [€/MWh],Österreich [€/MWh],Polen [€/MWh],Schweden 4 [€/MWh],Schweiz [€/MWh],Tschechien [€/MWh],DE/AT/LU [€/MWh],Italien (Nord) [€/MWh],Slowenien [€/MWh],Ungarn [€/MWh]
9,01.10.2025 00:00,01.10.2025 00:15,102.6,95.01,102.68,102.6,102.44,102.08,102.55,68.61,108.87,98.95,58.11,101,97.21,-,113.6,109.1,108.98
10,01.10.2025 00:15,01.10.2025 00:30,92.24,87.2,92.25,92.24,92.1,91.65,92.17,67.13,97.08,91.13,54.3,101,88.1,-,108.55,97.24,97.08
11,01.10.2025 00:30,01.10.2025 00:45,86.03,79.5,80.47,86.03,85.9,63.14,82.69,64.43,97.07,81.79,53.05,101,78.98,-,101.61,96.22,90.97
12,01.10.2025 00:45,01.10.2025 01:00,85.39,80.86,79.53,85.39,85.27,61.25,81.86,63.94,97.04,102.85,53.35,101,77.95,-,97.04,96.14,90.6
13,01.10.2025 01:00,01.10.2025 01:15,89.99,85.14,89.28,89.99,89.85,86.91,89.54,65.59,92.78,93.98,52.23,98.46,87.92,-,108.61,92.51,91.15
14,01.10.2025 01:15,01.10.2025 01:30,86.03,82.21,84.28,86.03,85.91,78.45,84.93,64.21,92.9,95.24,52.97,98.46,80.93,-,99.68,92.23,88.89
15,01.10.2025 01:30,01.10.2025 01:45,85.03,81.27,82.64,85.03,84.9,75.02,83.56,63.9,91.63,97.09,51.32,98.46,80.42,-,93.82,91.04,87.86
16,01.10.2025 01:45,01.10.2025 02:00,84.09,80.25,80.06,84.09,83.95,67.7,81.69,63.64,90.92,105.44,46.82,98.46,80.01,-,92.56,90.44,87.22
17,01.10.2025 02:00,01.10.2025 02:15,85.41,80.3,79.52,85.41,85.29,61.57,81.87,63.66,97.05,100.39,52.53,98,78.01,-,102,96.16,90.62
18,01.10.2025 02:15,01.10.2025 02:30,85,80.03,79.21,85,84.88,61.51,81.51,63.57,97.04,99.77,52.62,98,77.22,-,102.1,96.09,90.35
19,01.10.2025 02:30,01.10.2025 02:45,84.54,76.77,72.41,84.54,84.43,36.82,77.42,63.55,97.05,98.55,52.55,98,79.1,-,102,96.56,90.87